# Generated by Django 2.2 on 2019-07-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190712_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StuForm',
        ),
    ]
